### ISSUE TITLE
Ardour won't compile on OSX 10.11

### ISSUE THREAD

**Issue by rodneyrod** [david0/homebrew-audio#7]
Get the following error when trying to compile Ardour5:

Last 15 lines from /Users/USERNAME/Library/Logs/Homebrew/ardour5/02.waf:
../libs/pbd/locale_guard.cc:68:72: error: 'numeric' is unavailable: introduced in macOS 10.9
                        std::locale::global (std::locale (old_cpp_locale, "C", std::locale::numeric));
                                                                                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:74:9: note: 'numeric' has been explicitly marked unavailable here
        numeric  = LC_NUMERIC_MASK,
        ^
1 error generated.
Waf: Leaving directory `/private/tmp/ardour5-20170112-1982-ymrppt/build'
Build failed
 -> task in 'libpbd' failed (exit status 1): 
	{task 4345194320: cxx locale_guard.cc -> locale_guard.cc.2.o}
['clang++', '-I/private/tmp/ardour5-20170112-1982-ymrppt', '-DHAVE_RF64_RIFF', '-DWAF_BUILD', '-g', '-fshow-column', '-DARCH_X86', '-DBUILD_VECLIB_OPTIMIZATIONS', '-DMAC_OS_X_VERSION_MAX_ALLOWED=1090', '-mmacosx-version-min=10.8', '-Wall', '-Wpointer-arith', '-Wcast-qual', '-Wcast-align', '-Wno-unused-parameter', '-DBOOST_SYSTEM_NO_DEPRECATED', '-D_ISOC9X_SOURCE', '-D_LARGEFILE64_SOURCE', '-D_FILE_OFFSET_BITS=64', '-DENABLE_NLS', '-DPROGRAM_NAME="Ardour"', u'-DPROGRAM_VERSION="5"', '--stdlib=libc++', '-Wno-c++11-narrowing', '-std=c++11', '-DCARBON_FLAT_HEADERS', '-Qunused-arguments', '-Woverloaded-virtual', '-Wno-mismatched-tags', '-Wno-cast-align', '-Wno-unused-local-typedefs', '-D__STDC_LIMIT_MACROS', '-D__STDC_FORMAT_MACROS', '-DCANVAS_COMPATIBILITY', '-DCANVAS_DEBUG', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-msse', '-msse2', '-F/System/Library/Frameworks', '-F/Library/Frameworks', '-I/private/tmp/ardour5-20170112-1982-ymrppt/build/libs/pbd', '-I/private/tmp/ardour5-20170112-1982-ymrppt/libs/pbd', '-I/usr/local/Cellar/pcre/8.39/include', '-I/usr/local/Cellar/glib/2.50.2/include/glib-2.0', '-I/usr/local/Cellar/glib/2.50.2/lib/glib-2.0/include', '-I/usr/local/opt/gettext/include', '-I/usr/local/Cellar/libsigc++/2.10.0/include/sigc++-2.0', '-I/usr/local/Cellar/libsigc++/2.10.0/lib/sigc++-2.0/include', '-I/usr/local/Cellar/glibmm/2.50.0/include/glibmm-2.4', '-I/usr/local/Cellar/glibmm/2.50.0/lib/glibmm-2.4/include', '-I/usr/include/libxml2', '-I/usr/local/Cellar/libsndfile/1.0.26/include', '-I/usr/local/Cellar/glibmm/2.50.0/include/giomm-2.4', '-I/usr/local/Cellar/glibmm/2.50.0/lib/giomm-2.4/include', '-I/private/tmp/ardour5-20170112-1982-ymrppt/build', '-DNEED_INTL=1', '-DHAVE_COREAUDIO=1', '-DAUDIOUNIT_SUPPORT=1', '-DTOP_MENUBAR=1', '-DINTERNAL_SHARED_LIBS=1', '-DHAVE_DLOPEN=1', '-DHAVE_GLIB=1', '-DHAVE_GTHREAD=1', '-DHAVE_GLIBMM=1', '-DHAVE_SNDFILE=1', '-DHAVE_GIOMM=1', '-DHAVE_CURL=1', '-DHAVE_LO=1', '-DHAVE_TAGLIB=1', '-DHAVE_VAMPSDK=1', '-DHAVE_VAMPHOSTSDK=1', '-DHAVE_RUBBERBAND=1', '-DEXPORT_VISIBILITY_HIDDEN=False', '-DPHONE_HOME=1', '-DENABLE_NLS=1', '-D_DARWIN_C_SOURCE=1', '-DCONFIG_ARCH="x86_64"', '-DHAVE_LIBS_APPLEUTILITY=1', '-DHAVE_LIBS_CLEARLOOKS_NEWER=1', '-DHAVE_LIBS_QM_DSP=1', '-DHAVE_FFTW3F=1', '-DHAVE_AUBIO=1', '-DHAVE_AUBIO4=1', '-DHAVE_LIBS_VAMP_PLUGINS=1', '-DHAVE_LIBS_LIBLTC=1', '-DHAVE_LIBS_LUA=1', '-DHAVE_LIBS_PTFORMAT=1', '-DHAVE_XML=1', '-DHAVE_SIGCPP=1', '-DHAVE_EXECINFO=1', '-DHAVE_POSIX_MEMALIGN=1', '-DHAVE_LOCALTIME_R=1', '-DHAVE_LIBS_PBD=1', '-DHAVE_LIBS_MIDIPP2=1', '-DHAVE_LIBS_EVORAL=1', '-DHAVE_CONTROL_PROTOCOL=1', '-DHAVE_FADERPORT=1', '-DHAVE_GENERIC_MIDI=1', '-DHAVE_MACKIE=1', '-DHAVE_LIBS_SURFACES=1', '-DHAVE_2IN2OUT=1', '-DHAVE_1IN2OUT=1', '-DHAVE_VBAP=1', '-DHAVE_STEREOBALANCE=1', '-DHAVE_LIBS_PANNERS=1', '-DHAVE_JACK=1', '-DHAVE_JACK_METADATA=1', '-DHAVE_LIBS_BACKENDS=1', '-DHAVE_LIBS_TIMECODE=1', '-DHAVE_LRDF=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_LV2=1', '-DHAVE_LV2_1_2_0=1', '-DHAVE_LV2_1_10_0=1', '-DHAVE_SERD=1', '-DHAVE_SORD=1', '-DHAVE_SRATOM=1', '-DHAVE_LILV=1', '-DHAVE_LILV_0_16_0=1', '-DHAVE_LILV_0_19_2=1', '-DHAVE_LILV_0_21_3=1', '-DHAVE_SUIL=1', '-DLV2_SUPPORT=1', '-DLV2_EXTENDED=1', '-DHAVE_OGG=1', '-DHAVE_FLAC=1', '-DUSE_RUBBERBAND=1', '-DCURRENT_SESSION_FILE_VERSION=3002', '-DHAVE_SYS_STATVFS_H=1', '-DHAVE_UNISTD=1', '-DHAVE_BOOST_SCOPED_PTR_HPP=1', '-DHAVE_BOOST_PTR_CONTAINER_PTR_LIST_HPP=1', '-DHAVE_LIBS_ARDOUR=1', '-DHAVE_GTKMM=1', '-DHAVE_GTK=1', '-DHAVE_LIBS_GTKMM2EXT=1', '-DHAVE_FFTW35F=1', '-DHAVE_BOOST_FORMAT_HPP=1', '-DHAVE_LIBS_AUDIOGRAPHER=1', '-DHAVE_CAIROMM=1', '-DHAVE_LIBS_CANVAS=1', '-DHAVE_LV2_1_0_0=1', '-DHAVE_LIBS_PLUGINS_REASONABLESYNTH_LV2=1', '-DHAVE_CAIRO=1', '-DHAVE_LIBS_PLUGINS_A_COMP_LV2=1', '-DHAVE_LIBS_PLUGINS_A_DELAY_LV2=1', '-DHAVE_LIBS_PLUGINS_A_EQ_LV2=1', '-DHAVE_LIBS_PLUGINS_A_REVERB_LV2=1', '-DHAVE_FONTCONFIG=1', '-DHAVE_COCOA_LIVE_RESIZING=1', '-DHAVE_BOOST_SHARED_PTR_HPP=1', '-DHAVE_BOOST_WEAK_PTR_HPP=1', '-DHAVE_GTK2_ARDOUR=1', '-DHAVE_EXPORT=1', '-DHAVE_MIDI_MAPS=1', '-DHAVE_MCP=1', '-DHAVE_PATCHFILES=1', '-DHAVE_SCRIPTS=1', '-DHAVE_HEADLESS=1', '-DHAVE_SESSION_UTILS=1', '-DHAVE_LIBS_FST=1', '-DHAVE_LIBS_VFORK=1', '-DHAVE_LIBS_ARDOURALSAUTIL=1', '-DHAVE_CFGTOOL=1', '-DHAVE_READLINE=1', '-DHAVE_TOOLS_LUADEVEL=1', '-DLIBPBD_DLL_EXPORTS=1', '-DPACKAGE="libpbd4"', '-D_REENTRANT', '../libs/pbd/locale_guard.cc', '-c', '-o', 'libs/pbd/locale_guard.cc.2.o']
Git version: 5.0
